"""
Evaluate predictions with retrieved candidates.

Reads prediction_with_candidates.jsonl files generated by main.py during inference,
computes exact match (EM) and edit similarity (ES) per sample, sorts results
from lowest to highest EM/ES score, and saves everything to a JSON file
for analysis and insight generation.

Usage:
    python evaluate_with_candidates.py \
        --input_file results/baseline/cceval_python/prediction_with_candidates.jsonl \
        --output_file results/baseline/cceval_python/evaluation_analysis.json

    # Or evaluate all datasets under a results directory:
    python evaluate_with_candidates.py \
        --results_dir results/baseline \
        --output_dir results/baseline/analysis
"""

import os
import json
import argparse
from difflib import SequenceMatcher
from collections import OrderedDict

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
    HAS_OPENPYXL = True
except ImportError:
    HAS_OPENPYXL = False
    print("[WARNING] openpyxl not installed. Excel output will be skipped.")
    print("  Install with: pip install openpyxl")


def normalize_code(code: str) -> str:
    """Normalize code by stripping whitespace per line and removing blank lines."""
    lines = [l.strip() for l in code.split("\n") if l.strip()]
    return "\n".join(lines)


def compute_exact_match(pred: str, target: str) -> int:
    """
    Compute exact match after normalizing both prediction and target.
    Returns 1 if match, 0 otherwise.
    """
    pred_norm = normalize_code(pred)
    target_norm = normalize_code(target)
    return 1 if pred_norm == target_norm else 0


def compute_exact_match_prefix(pred: str, target: str) -> int:
    """
    Compute prefix-based exact match (as used in main.py for github_eval).
    Compares the shorter prefix of both after removing all whitespace.
    Returns 1 if match, 0 otherwise.
    """
    pred_flat = "".join(pred.split())
    target_flat = "".join(target.split())
    min_len = min(len(pred_flat), len(target_flat))
    if min_len == 0:
        return 1 if len(pred_flat) == len(target_flat) else 0
    return 1 if pred_flat[:min_len] == target_flat[:min_len] else 0


def compute_edit_similarity(pred: str, target: str) -> float:
    """
    Compute edit similarity between prediction and target using SequenceMatcher.
    Returns a float between 0.0 and 1.0.
    """
    return SequenceMatcher(None, pred, target).ratio()


def save_to_excel(summary, evaluated, excel_file):
    """
    Save evaluation results to an Excel file with two sheets:
    - Summary: overall metrics
    - Results: per-sample details sorted by edit_similarity (ascending)
    """
    if not HAS_OPENPYXL:
        print("  [SKIP] Excel output skipped (openpyxl not installed)")
        return

    wb = Workbook()

    # --- Styles ---
    header_font = Font(name="Arial", bold=True, size=11, color="FFFFFF")
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    cell_alignment = Alignment(vertical="top", wrap_text=True)
    thin_border = Border(
        left=Side(style="thin"),
        right=Side(style="thin"),
        top=Side(style="thin"),
        bottom=Side(style="thin"),
    )
    green_fill = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
    red_fill = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")

    # ============== Sheet 1: Summary ==============
    ws_summary = wb.active
    ws_summary.title = "Summary"

    summary_headers = ["Metric", "Value"]
    for col, h in enumerate(summary_headers, 1):
        cell = ws_summary.cell(row=1, column=col, value=h)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment
        cell.border = thin_border

    summary_rows = [
        ("Total Samples", summary["total_samples"]),
        ("Exact Match Rate (%)", summary["exact_match_rate"]),
        ("Exact Match Prefix Rate (%)", summary["exact_match_prefix_rate"]),
        ("Avg Edit Similarity", summary["avg_edit_similarity"]),
        ("Num Correct", summary["num_correct"]),
        ("Num Incorrect", summary["num_incorrect"]),
    ]
    for row_idx, (metric, value) in enumerate(summary_rows, 2):
        cell_m = ws_summary.cell(row=row_idx, column=1, value=metric)
        cell_v = ws_summary.cell(row=row_idx, column=2, value=value)
        cell_m.border = thin_border
        cell_v.border = thin_border
        cell_m.font = Font(name="Arial", bold=True, size=10)
        cell_v.font = Font(name="Arial", size=10)

    ws_summary.column_dimensions["A"].width = 30
    ws_summary.column_dimensions["B"].width = 18

    # ============== Sheet 2: Results ==============
    ws_results = wb.create_sheet(title="Results")

    result_headers = [
        "Rank", "Task ID", "Exact Match", "EM Prefix",
        "Edit Similarity", "Input", "Target", "Prediction", "Candidates"
    ]
    for col, h in enumerate(result_headers, 1):
        cell = ws_results.cell(row=1, column=col, value=h)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment
        cell.border = thin_border

    for row_idx, item in enumerate(evaluated, 2):
        # Serialize candidates as readable JSON string
        candidates_str = json.dumps(item.get("candidates", []), ensure_ascii=False, indent=1)

        row_data = [
            item.get("rank", ""),
            item.get("task_id", ""),
            item.get("exact_match", 0),
            item.get("exact_match_prefix", 0),
            item.get("edit_similarity", 0),
            item.get("input", ""),
            item.get("target", ""),
            item.get("pred", ""),
            candidates_str,
        ]

        for col, val in enumerate(row_data, 1):
            cell = ws_results.cell(row=row_idx, column=col, value=val)
            cell.alignment = cell_alignment
            cell.border = thin_border
            cell.font = Font(name="Arial", size=9)

        # Color-code Exact Match column
        em_cell = ws_results.cell(row=row_idx, column=3)
        if item.get("exact_match", 0) == 1:
            em_cell.fill = green_fill
        else:
            em_cell.fill = red_fill

    # Set column widths
    col_widths = {
        "A": 6,   # Rank
        "B": 25,  # Task ID
        "C": 12,  # Exact Match
        "D": 10,  # EM Prefix
        "E": 14,  # Edit Similarity
        "F": 50,  # Input
        "G": 40,  # Target
        "H": 40,  # Prediction
        "I": 60,  # Candidates
    }
    for col_letter, width in col_widths.items():
        ws_results.column_dimensions[col_letter].width = width

    # Freeze header row
    ws_results.freeze_panes = "A2"

    # Auto-filter
    ws_results.auto_filter.ref = f"A1:I{len(evaluated) + 1}"

    # Save
    wb.save(excel_file)


def evaluate_single_file(input_file: str, output_file: str):
    """
    Evaluate a single prediction_with_candidates.jsonl file.

    For each sample, computes:
    - exact_match: normalized line-level comparison
    - exact_match_prefix: whitespace-flattened prefix comparison
    - edit_similarity: SequenceMatcher ratio

    Results are sorted by edit_similarity (ascending), so worst predictions come first
    for easy insight and debugging.

    Output JSON structure:
    {
        "summary": {
            "total_samples": int,
            "exact_match_rate": float (percentage),
            "exact_match_prefix_rate": float (percentage),
            "avg_edit_similarity": float,
            "num_correct": int,
            "num_incorrect": int
        },
        "results": [
            {
                "rank": int,
                "task_id": str,
                "exact_match": int (0 or 1),
                "exact_match_prefix": int (0 or 1),
                "edit_similarity": float,
                "input": str,
                "target": str,
                "pred": str,
                "candidates": [
                    {"file_path": str, "description": str, "code_content": str},
                    ...
                ]
            },
            ...
        ]
    }
    """
    # Load data
    samples = []
    with open(input_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                samples.append(json.loads(line))

    if not samples:
        print(f"  [WARNING] No samples found in {input_file}")
        return

    print(f"  Loaded {len(samples)} samples from {input_file}")

    # Compute metrics per sample
    evaluated = []
    for sample in samples:
        pred = sample.get("pred", "")
        target = sample.get("target", "")

        em = compute_exact_match(pred, target)
        em_prefix = compute_exact_match_prefix(pred, target)
        es = compute_edit_similarity(pred, target)

        evaluated.append({
            "task_id": sample.get("task_id", ""),
            "exact_match": em,
            "exact_match_prefix": em_prefix,
            "edit_similarity": round(es, 6),
            "input": sample.get("input", ""),
            "target": target,
            "pred": pred,
            "candidates": sample.get("candidates", []),
        })

    # Sort by edit_similarity ascending (worst first for insight)
    evaluated.sort(key=lambda x: (x["edit_similarity"], x["exact_match"]))

    # Add rank
    for rank, item in enumerate(evaluated, 1):
        item["rank"] = rank
        # Reorder keys for readability
        item_ordered = OrderedDict([
            ("rank", item["rank"]),
            ("task_id", item["task_id"]),
            ("exact_match", item["exact_match"]),
            ("exact_match_prefix", item["exact_match_prefix"]),
            ("edit_similarity", item["edit_similarity"]),
            ("input", item["input"]),
            ("target", item["target"]),
            ("pred", item["pred"]),
            ("candidates", item["candidates"]),
        ])
        evaluated[rank - 1] = item_ordered

    # Compute summary
    total = len(evaluated)
    num_correct = sum(1 for x in evaluated if x["exact_match"] == 1)
    num_correct_prefix = sum(1 for x in evaluated if x["exact_match_prefix"] == 1)
    avg_es = sum(x["edit_similarity"] for x in evaluated) / total

    summary = OrderedDict([
        ("total_samples", total),
        ("exact_match_rate", round(num_correct / total * 100, 4)),
        ("exact_match_prefix_rate", round(num_correct_prefix / total * 100, 4)),
        ("avg_edit_similarity", round(avg_es, 6)),
        ("num_correct", num_correct),
        ("num_incorrect", total - num_correct),
    ])

    # Build output
    output = OrderedDict([
        ("summary", summary),
        ("results", evaluated),
    ])

    # Write output
    os.makedirs(os.path.dirname(output_file) if os.path.dirname(output_file) else ".", exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    # Write Excel output
    excel_file = output_file.replace(".json", ".xlsx")
    save_to_excel(summary, evaluated, excel_file)

    print(f"  EM: {summary['exact_match_rate']}% | EM(prefix): {summary['exact_match_prefix_rate']}% | Avg ES: {summary['avg_edit_similarity']}")
    print(f"  Correct: {num_correct}/{total} | Incorrect: {total - num_correct}/{total}")
    print(f"  Results saved to: {output_file}")
    print(f"  Excel saved to:   {excel_file}")
    print()

    return summary


def evaluate_results_dir(results_dir: str, output_dir: str = None):
    """
    Walk through a results directory and evaluate all prediction_with_candidates.jsonl files found.
    """
    if output_dir is None:
        output_dir = os.path.join(results_dir, "analysis")

    all_summaries = {}

    for root, dirs, files in os.walk(results_dir):
        for fname in files:
            if fname == "prediction_with_candidates.jsonl":
                input_file = os.path.join(root, fname)

                # Determine relative path for naming
                rel_path = os.path.relpath(root, results_dir)
                output_file = os.path.join(output_dir, rel_path, "evaluation_analysis.json")

                print(f"Evaluating: {rel_path}")
                summary = evaluate_single_file(input_file, output_file)
                if summary:
                    all_summaries[rel_path] = dict(summary)

    # Save overall summary
    if all_summaries:
        overall_file = os.path.join(output_dir, "overall_summary.json")
        with open(overall_file, "w", encoding="utf-8") as f:
            json.dump(all_summaries, f, ensure_ascii=False, indent=2)
        print(f"\n{'='*60}")
        print(f"Overall summary saved to: {overall_file}")
        print(f"{'='*60}")

        # Print summary table
        print(f"\n{'Dataset':<40} {'EM%':>8} {'EM_pfx%':>8} {'Avg ES':>8} {'Total':>6}")
        print("-" * 72)
        for name, s in sorted(all_summaries.items()):
            print(f"{name:<40} {s['exact_match_rate']:>8.2f} {s['exact_match_prefix_rate']:>8.2f} {s['avg_edit_similarity']:>8.4f} {s['total_samples']:>6}")


def main():
    parser = argparse.ArgumentParser(
        description="Evaluate predictions with retrieved candidates. "
                    "Computes exact match, edit similarity, sorts by score, "
                    "and saves comprehensive results for analysis."
    )

    parser.add_argument(
        "--input_file", type=str, default=None,
        help="Path to a single prediction_with_candidates.jsonl file"
    )
    parser.add_argument(
        "--output_file", type=str, default=None,
        help="Path to save the evaluation JSON output (used with --input_file)"
    )
    parser.add_argument(
        "--results_dir", type=str, default=None,
        help="Path to a results directory to evaluate all datasets within"
    )
    parser.add_argument(
        "--output_dir", type=str, default=None,
        help="Path to save analysis outputs (used with --results_dir)"
    )

    args = parser.parse_args()

    if args.input_file:
        # Single file mode
        output_file = args.output_file
        if output_file is None:
            base_dir = os.path.dirname(args.input_file)
            output_file = os.path.join(base_dir, "evaluation_analysis.json")
        evaluate_single_file(args.input_file, output_file)

    elif args.results_dir:
        # Directory mode
        evaluate_results_dir(args.results_dir, args.output_dir)

    else:
        print("Error: Please provide either --input_file or --results_dir")
        print()
        parser.print_help()
        exit(1)


if __name__ == "__main__":
    main()
