"""Versioned AST chunks and completion cuts for repository-retriever training.

Gold is used only to select supervised tasks and record dependency evidence.
Candidate retrieval uses the visible prefix. Evidence is static and does not
claim a positive generator utility label.
"""
from dataclasses import dataclass
from bisect import bisect_right
from functools import lru_cache
import posixpath
import re

import tree_sitter as ts
import tree_sitter_java
import tree_sitter_python

from src.data.audit_completion_data import source_hash

SCHEMA = "ast_repo_pool_v3"
SCOPES = {"class_definition", "function_definition", "class_declaration",
          "method_declaration", "constructor_declaration", "interface_declaration"}
STATEMENTS = {"expression_statement", "return_statement", "throw_statement",
              "local_variable_declaration", "assignment", "augmented_assignment"}
NAMES = re.compile(r"[A-Za-z_$][A-Za-z0-9_$]*")


@dataclass(frozen=True)
class DataConfig:
    min_files: int = 4
    max_files: int = 200
    min_substantive_files: int = 3
    min_production_files: int = 2
    min_file_code_lines: int = 12
    min_repo_code_lines: int = 120
    max_repo_code_lines: int = 200_000
    max_file_bytes: int = 500_000
    max_tokenization_bytes: int = 16_384  # Bound work per probe, not a source-file truncation.
    chunk_tokens: int = 384
    min_chunk_tokens: int = 96  # Soft merge target; residual short chunks are retained.
    retriever_tokens: int = 508
    cross_file_budget_tokens: int = 2344
    max_cross_file_snippets: int = 10
    min_prefix_tokens: int = 64
    min_prefix_lines: int = 8
    max_left_context_tokens: int = 2048
    left_tail_tokens: int = 1536
    left_hint_tokens: int = 512
    # Test audit: p10 is 5--8 tokens across CCEval/RepoEval. Exclude only
    # the easiest tiny completions by default.
    min_target_tokens: int = 6
    line_target_tokens: int = 64
    api_target_tokens: int = 160
    targets_per_repo: int = 5
    max_target_spans_per_file: int = 128
    max_target_spans_per_repo: int = 512
    pool_size: int = 64
    repos_per_epoch: int = 2_000
    dependent_target_probability: float = 0.8
    max_target_attempts: int = 16

    def __post_init__(self):
        if self.min_files < 4:
            raise ValueError("Training excludes repositories with only 1–3 code files")
        if self.max_files < self.min_files:
            raise ValueError("max_files must be at least min_files")
        if self.max_repo_code_lines < self.min_repo_code_lines:
            raise ValueError("max_repo_code_lines must be at least min_repo_code_lines")
        if self.min_production_files < 1:
            raise ValueError("min_production_files must be positive")
        if self.left_tail_tokens > self.max_left_context_tokens:
            raise ValueError("left_tail_tokens cannot exceed max_left_context_tokens")
        if self.left_hint_tokens > self.max_left_context_tokens:
            raise ValueError("left_hint_tokens cannot exceed max_left_context_tokens")
        if any(value <= 0 for name, value in vars(self).items()
               if name not in {"dependent_target_probability"}):
            raise ValueError("Data limits must be positive")
        if not 0.0 <= self.dependent_target_probability <= 1.0:
            raise ValueError("dependent_target_probability must be in [0, 1]")
        if self.min_chunk_tokens > self.chunk_tokens:
            raise ValueError('Soft chunk floor cannot exceed hard cap')


def walk(root):
    stack = [root]
    while stack:
        node = stack.pop()
        yield node
        stack.extend(reversed(node.named_children))


def key(path):
    return posixpath.normpath(path.replace("\\", "/"))


GENERATED_PATH_PARTS = {
    "generated", "__generated__", "autogenerated", "auto-generated",
}
GENERATED_HEADER = re.compile(
    r"(?:@generated|auto[- ]generated|generated\s+by|do\s+not\s+edit|"
    r"this\s+file\s+was\s+generated)", re.I,
)
TEST_PATH_PARTS = {"test", "tests", "__tests__", "testdata", "test_data", "fixtures"}


def is_generated_source(path, code):
    """Reject explicit generated files; a normal ``gen`` package is allowed."""
    normalized = key(path).lower()
    parts = set(normalized.split("/"))
    filename = normalized.rsplit("/", 1)[-1]
    header = "\n".join(code.splitlines()[:40])
    return (bool(parts.intersection(GENERATED_PATH_PARTS))
            or ".generated." in filename
            or bool(GENERATED_HEADER.search(header)))


def is_test_source(path):
    """Classify tests for repository quality, without deleting them as input noise."""
    normalized = key(path).lower()
    parts = set(normalized.split("/"))
    filename = normalized.rsplit("/", 1)[-1]
    return (bool(parts.intersection(TEST_PATH_PARTS))
            or filename.startswith("test_")
            or filename.startswith("test.")
            or filename.endswith(("_test.py", "_test.java"))
            or filename in {"test.py", "test.java"})


def valid_source(path, code, language, config):
    extension = ".py" if language == "python" else ".java"
    parts = set(key(path).lower().split("/"))
    return (key(path).lower().endswith(extension) and bool(code.strip())
            and len(code.encode("utf-8")) <= config.max_file_bytes
            and not is_generated_source(path, code)
            and not parts.intersection({"node_modules", ".git", "__pycache__", "vendor", "venv", ".venv"}))


class SourceFile:
    def __init__(self, path, code, language, tokenizer, retriever_tokenizer=None,
                 config=DataConfig()):
        self.path, self.code, self.language = key(path), code, language
        self.raw = code.encode("utf-8")
        self.tokenizer, self.retriever_tokenizer, self.config = tokenizer, retriever_tokenizer, config
        grammar = tree_sitter_python if language == "python" else tree_sitter_java
        self.tree = ts.Parser(ts.Language(grammar.language())).parse(self.raw)
        self.nodes = list(walk(self.tree.root_node))
        self.digest = source_hash(code)
        self._counts = {}
        self._symbols = None
        self.import_nodes = [n for n in self.nodes if n.type in {
            'import_statement', 'import_from_statement', 'import_declaration', 'package_declaration'}]
        self.import_ends = sorted(n.end_byte for n in self.import_nodes)
        self._import_files = None
        self._import_cache = {}

    def text(self, node):
        return self.raw[node.start_byte:node.end_byte].decode("utf-8")

    def count(self, start, end):
        pair = (start, end)
        if pair not in self._counts:
            self._counts[pair] = len(self.tokenizer.encode(
                self.raw[start:end].decode("utf-8"), add_special_tokens=False))
        return self._counts[pair]

    def fits(self, start, end):
        if end - start > self.config.max_tokenization_bytes:
            return False
        if self.count(start, end) > self.config.chunk_tokens:
            return False
        return self.retriever_tokenizer is None or len(self.retriever_tokenizer.encode(
            self.raw[start:end].decode("utf-8"), add_special_tokens=False)) <= self.config.retriever_tokens

    def headers(self, node, start, end):
        result = []
        parent = node
        while parent is not None:
            if parent.type in SCOPES:
                body = parent.child_by_field_name("body")
                if body is not None and parent.start_byte < body.start_byte:
                    a, b = parent.start_byte, body.start_byte
                    # Include a scope header as provenance even when this
                    # chunk begins at the header; interior chunks also keep
                    # the same header as retrieval metadata.
                    if a < b <= end:
                        result.append({"start": a, "end": b,
                                       "text": self.raw[a:b].decode("utf-8"), "type": parent.type})
            parent = parent.parent
        return list(reversed(result))

    def chunks(self):
        """Pack adjacent AST siblings; retain scope headers as separate source spans."""
        chunks = []

        def emit(start, end, kind, node):
            if start >= end or not self.raw[start:end].strip():
                return
            chunks.append({"path": self.path, "start": start, "end": end,
                           "text": self.raw[start:end].decode("utf-8"), "type": kind,
                           "scope_headers": self.headers(node, start, end),
                           "source_sha256": self.digest})

        def windows(start, end, node):
            # Exact source slices even for giant strings/one-line generated code.
            text = self.raw[start:end].decode("utf-8")
            offset = start
            while text:
                lo, hi = 1, min(len(text), self.config.max_tokenization_bytes)
                best = 0
                while lo <= hi:
                    mid = (lo + hi)//2
                    size = len(text[:mid].encode("utf-8"))
                    if self.fits(offset, offset + size):
                        best, lo = mid, mid + 1
                    else:
                        hi = mid - 1
                if not best:
                    raise ValueError("One Unicode character exceeds chunk token caps")
                # Prefer a complete physical line when one fits this window.
                boundary = text.rfind("\n", 0, best)
                if boundary > 0:
                    best = boundary + 1
                size = len(text[:best].encode("utf-8"))
                while best > 0 and not self.fits(offset, offset + size):
                    best -= 1
                    size = len(text[:best].encode('utf-8'))
                if not best:
                    raise ValueError('No bounded Unicode window fits')
                # Keep a short final tail as-is. Moving the boundary one
                # character at a time and re-tokenizing the entire tail is
                # quadratic on large source windows; residual short chunks are
                # explicitly allowed and are never dropped.
                emit(offset, offset + size, "bounded_source_window", node)
                offset += size
                text = text[best:]

        def partition(node, depth=0):
            if depth > 128:
                windows(node.start_byte, node.end_byte, node)
                return
            if self.fits(node.start_byte, node.end_byte):
                emit(node.start_byte, node.end_byte, node.type, node)
                return
            # Splitting arbitrary expression children loses operators, quotes,
            # and control-flow branches. Only containers/scopes admit AST packing.
            if node.type not in SCOPES | {'block', 'class_body', 'module', 'program'}:
                windows(node.start_byte, node.end_byte, node)
                return
            body = node.child_by_field_name("body")
            # Some grammars attach comments between a scope header and its
            # block directly to the scope, rather than to ``body``. Add those
            # comments back in source order so the header/comment bytes remain
            # part of a chunk.
            if body is not None:
                children = list(body.named_children)
                children.extend(comment for comment in node.named_children
                                if comment.type in {"comment", "line_comment", "block_comment"}
                                and node.start_byte <= comment.start_byte <= body.end_byte)
                children.sort(key=lambda child: (child.start_byte, child.end_byte))
            else:
                children = list(node.named_children)
            if not children:
                windows(node.start_byte, node.end_byte, node)
                return
            pack_children(children, depth + 1, prefix_start=node.start_byte)

        def pack_children(children, depth=0, prefix_start=None):
            group = []
            emitted_start = len(chunks)
            def flush():
                nonlocal prefix_start
                if group:
                    start = group[0].start_byte if prefix_start is None else prefix_start
                    emit(start, group[-1].end_byte, "ast_sibling_group", group[0])
                    group.clear()
                    prefix_start = None
            for child in children:
                if not self.fits(child.start_byte, child.end_byte):
                    flush()
                    if prefix_start is not None:
                        emit(prefix_start, child.start_byte, "scope_header", child)
                        prefix_start = None
                    partition(child, depth)
                else:
                    if group:
                        start = group[0].start_byte if prefix_start is None else prefix_start
                        full = not self.fits(start, child.end_byte)
                        # Keep substantial definitions distinct. Tiny getters,
                        # fields/imports may share a same-scope neighboring chunk.
                        substantial_boundary = (child.type in SCOPES
                            and self.count(child.start_byte, child.end_byte) >= self.config.min_chunk_tokens
                            and self.count(start, group[-1].end_byte) >= self.config.min_chunk_tokens)
                        if full or substantial_boundary:
                            flush()
                    group.append(child)
            flush()
            # A short final sibling group can be absorbed only when both groups
            # share the same immediate AST parent and their full source span fits.
            if len(chunks) - emitted_start >= 2:
                previous, tail = chunks[-2:]
                if (previous['type'] == tail['type'] == 'ast_sibling_group'
                        and previous['scope_headers'] == tail['scope_headers']
                        and self.count(tail['start'], tail['end']) < self.config.min_chunk_tokens
                        and self.fits(previous['start'], tail['end'])):
                    old = self.raw[previous['start']:tail['end']].decode('utf-8')
                    previous.update(end=tail['end'], text=old)
                    chunks.pop()

        if self.tree.root_node.has_error:
            windows(0, len(self.raw), self.tree.root_node)
            for chunk in chunks:
                chunk["type"] = "parse_error_window"
        else:
            pack_children(list(self.tree.root_node.named_children))
        # The AST naturally produces tiny leaves (decorators, imports, fields,
        # comments, and one-line statements). Pack adjacent spans when the
        # DeepSeek budget permits. If a residual span is still short, retain it:
        # chunk construction is lossless and never deletes source information.
        def merge(left, right):
            start, end = left['start'], right['end']
            if not self.fits(start, end):
                return False
            left.update({
                'end': end,
                'text': self.raw[start:end].decode('utf-8'),
                'type': 'ast_budget_group',
                'scope_headers': sorted(
                    {json_key: value for item in left['scope_headers'] + right['scope_headers']
                     for json_key, value in [((item['start'], item['end'], item['type']), item)]}.values(),
                    key=lambda item: (item['start'], item['end']),
                ),
            })
            return True

        changed = True
        while changed:
            changed = False
            for index, chunk in enumerate(list(chunks)):
                if self.count(chunk['start'], chunk['end']) >= self.config.min_chunk_tokens:
                    continue
                options = []
                if index:
                    options.append((abs(index - 1), index - 1))
                if index + 1 < len(chunks):
                    options.append((abs(index + 1 - index), index + 1))
                for _, neighbor_index in options:
                    a, b = sorted((index, neighbor_index))
                    if merge(chunks[a], chunks[b]):
                        chunks.pop(b)
                        changed = True
                        break
                if changed:
                    break
        return chunks

    def symbols(self):
        if self._symbols is not None:
            return self._symbols
        symbols = []
        for node in self.nodes:
            name = node.child_by_field_name("name")
            if node.type in SCOPES and name is not None:
                symbols.append({"name": self.text(name), "path": self.path,
                                "start": node.start_byte, "end": node.end_byte,
                                "type": node.type})
            if (self.language == 'java' and node.type == 'variable_declarator'
                    and name is not None and node.parent.type == 'field_declaration'):
                symbols.append({'name': self.text(name), 'path': self.path,
                                'start': node.parent.start_byte, 'end': node.parent.end_byte,
                                'type': 'field_declaration'})
            if self.language == "python" and node.type == "attribute":
                owner = node.child_by_field_name("object")
                name = node.child_by_field_name("attribute")
                parent = node.parent
                if (owner is not None and self.text(owner) in {"self", "cls"} and name is not None
                        and parent.type in {"assignment", "augmented_assignment"}
                        and parent.child_by_field_name("left") == node):
                    symbols.append({"name": self.text(name), "path": self.path,
                                    "start": parent.start_byte, "end": parent.end_byte,
                                    "type": "instance_field"})
        self._symbols = symbols
        return symbols

    def target_cuts(self):
        """Member suffixes, physical lines and multi-line API statements; exact bytes."""
        if self.tree.root_node.has_error:
            return []
        rows, seen = [], set()
        for node in self.nodes:
            variants = []
            if node.type in STATEMENTS:
                start = self.raw.rfind(b"\n", 0, node.start_byte) + 1
                end = self.raw.find(b"\n", node.start_byte)
                end = len(self.raw) if end < 0 else end
                # A full-line target only when the AST statement starts this line.
                if not self.raw[start:node.start_byte].strip():
                    variants.append((start, end, "line", self.config.line_target_tokens))
                    if node.end_byte > end and any(n.type in {"call", "method_invocation", "object_creation_expression"}
                                                  for n in walk(node)):
                        variants.append((start, node.end_byte, "api_statement", self.config.api_target_tokens))
            if node.type in {"attribute", "method_invocation", "field_access"}:
                name = node.child_by_field_name("attribute") or node.child_by_field_name("name") or node.child_by_field_name("field")
                if name is not None and self.raw[:name.start_byte].rstrip().endswith(b"."):
                    end = self.raw.find(b"\n", name.start_byte)
                    end = len(self.raw) if end < 0 else end
                    variants.append((name.start_byte, end, "member_suffix", self.config.line_target_tokens))
            for start, end, kind, cap in variants:
                if (start, end) in seen or start >= end:
                    continue
                if end - start > self.config.max_tokenization_bytes:
                    continue
                prefix, target = self.raw[:start], self.raw[start:end]
                # Bound the probe; the actual prompt is packed later from the
                # exact prefix. This avoids an unbounded tokenizer call here.
                prefix_probe = prefix[-self.config.max_tokenization_bytes:].decode(
                    "utf-8", errors="ignore")
                target_tokens = self.count(start, end)
                if (prefix.count(b"\n") < self.config.min_prefix_lines
                        or not self.config.min_target_tokens <= target_tokens <= cap
                        or len(self.tokenizer.encode(prefix_probe,
                                                     add_special_tokens=False)) < self.config.min_prefix_tokens):
                    continue
                if target.strip().startswith((b"#", b"//", b"/*", b'"""', b"'''")):
                    continue
                identifiers = [self.text(n) for n in walk(node)
                               if n.type in {"identifier", "type_identifier"}
                               and start <= n.start_byte < n.end_byte <= end]
                references = []
                for item in walk(node):
                    reference = None
                    if item.type == 'call':
                        callee = item.child_by_field_name('function')
                        if callee is not None and callee.type == 'identifier':
                            reference = callee
                    elif item.type == 'attribute':
                        reference = item.child_by_field_name('attribute')
                    elif item.type == 'method_invocation':
                        reference = item.child_by_field_name('name')
                    elif item.type == 'field_access':
                        reference = item.child_by_field_name('field')
                    elif item.type == 'type_identifier':
                        reference = item
                    if reference is not None and start <= reference.start_byte < reference.end_byte <= end:
                        references.append(self.text(reference))
                if not identifiers:
                    continue
                seen.add((start, end))
                rows.append({"start": start, "end": end, "kind": kind,
                             "node_type": node.type, "identifiers": sorted(set(identifiers)),
                             "reference_identifiers": sorted(set(references)),
                             "target_token_count": target_tokens,
                             "target_line_count": target.count(b"\n") + 1})
        return rows


def imported_paths(file, files, before):
    """Conservative path/module matching; returns evidence, not a type-checker proof."""
    if file._import_files is not files:
        file._import_files = files
        file._import_cache.clear()
    cache_key = bisect_right(file.import_ends, before)
    if cache_key in file._import_cache:
        return file._import_cache[cache_key]
    prefix = file.raw[:before].decode("utf-8")
    paths = {}
    if file.language == "python":
        imports = []
        for node in file.import_nodes:
            if node.type not in {"import_statement", "import_from_statement"} or node.end_byte > before:
                continue
            statement = file.text(node)
            match = re.match(r"from\s+([.\w]+)\s+import\s+(.+)|import\s+(.+)", statement, re.S)
            if match is None:
                continue
            if match[1]:
                imports.append((match[1], statement))
                for name in match[2].strip(" ()\n").split(','):
                    name = name.strip().split()
                    if name and name[0] != '*':
                        module = match[1] + ('' if match[1].endswith('.') else '.') + name[0]
                        imports.append((module, statement))
            else:
                for module in match[3].split(','):
                    imports.append((module.strip().split()[0], statement))
        for module, evidence in imports:
            relative = len(module)-len(module.lstrip('.'))
            suffix = module.lstrip('.').replace('.', '/')
            if not suffix:
                continue
            if relative:
                parent = posixpath.dirname(file.path)
                for _ in range(relative-1):
                    parent = posixpath.dirname(parent)
                endings = [key(posixpath.join(parent, suffix))]
            else:
                endings = [suffix]
            matches = [p for p in files if p != file.path and any(
                p == e + '.py' or p.endswith('/' + e + '.py')
                or p == e + '/__init__.py' or p.endswith('/' + e + '/__init__.py')
                for e in endings)]
            if len(matches) == 1:
                paths[matches[0]] = evidence
    else:
        package = re.search(r"\bpackage\s+([\w.]+)\s*;", prefix)
        imports = re.findall(r"\bimport\s+(?:static\s+)?([\w.*]+)\s*;", prefix)
        for p, other in files.items():
            if p == file.path:
                continue
            other_package = re.search(r"\bpackage\s+([\w.]+)\s*;", other.code)
            qualified = ((other_package[1] + '.') if other_package else '') + posixpath.basename(p)[:-5]
            evidence = next((i for i in imports if i == qualified or i.startswith(qualified + '.')
                             or (i.endswith('.*') and qualified.rsplit('.',1)[0] == i[:-2])), None)
            if evidence:
                paths[p] = 'import ' + evidence
            elif package and other_package and package[1] == other_package[1]:
                paths[p] = 'same package ' + package[1]
    file._import_cache[cache_key] = paths
    return paths


def dependency_evidence(file, cut, files, symbols):
    available = imported_paths(file, files, cut['start'])
    # Bare argument/local names (e.g. `name`) are not evidence that another
    # class's field of the same name supplies the target completion.
    names = set(cut['reference_identifiers'])
    # Local declarations are not external dependencies merely because names match.
    names -= {s['name'] for s in file.symbols()}
    evidence = []
    for symbol in symbols:
        if symbol['path'] in available and symbol['name'] in names:
            evidence.append({**symbol, 'import_evidence': available[symbol['path']],
                             'confidence': 'import_supported_symbol_match'})
    return evidence


@lru_cache(maxsize=65536)
def lexical(text):
    return tuple(NAMES.findall(text.lower()))


@lru_cache(maxsize=65536)
def encoder_text(tokenizer, cap, headers, core):
    text = headers + ('\n' if headers else '') + core
    return core if len(tokenizer.encode(text, add_special_tokens=False)) > cap else text


def candidate_text(chunk):
    # Headers are separately traceable; budget fitting happens when the pool is built.
    headers = '\n'.join(h['text'] for h in chunk['scope_headers'])
    return headers + ('\n' if headers else '') + chunk['text']


def mine_candidates(prefix, current_path, chunks, tokenizer, config=DataConfig()):
    from rank_bm25 import BM25Okapi
    candidates = [c for c in chunks if c['path'] != current_path]
    if not candidates:
        return []
    texts = [c.get('retrieval_text') or encoder_text(tokenizer, config.retriever_tokens,
              '\n'.join(h['text'] for h in c['scope_headers']), c['text']) for c in candidates]
    # Callers provide the already packed left context. Do not apply a second
    # character-based truncation here; the tokenizer budget is enforced by the
    # context packer before retrieval.
    query = prefix
    scores = BM25Okapi([lexical(t) or ['<empty>'] for t in texts]).get_scores(lexical(query))
    order = sorted(range(len(candidates)), key=lambda i: (-float(scores[i]), candidates[i]['path'], candidates[i]['start']))
    return [{**candidates[i], 'retrieval_text': texts[i], 'bm25_score': float(scores[i])}
            for i in order[:config.pool_size]]
